### PR TITLE
MGMT-14590: Adding pie charts

### PR DESCRIPTION
**Pull request by danmanor**
Converting cost by job type and cost by machine type to a pie chart

image

image

### CODE REVIEW

**Comment by rccrdpccl** [comment]
Looks good but are we replacing kibana by sending already-rendered-charts to slack? :sweat_smile:

**Comment by danmanor** [comment]
@rccrdpccl  Do you think its too much? I thought we send this data anyway, it might as well be nice looking.
@osherdp WDYT?

**Comment by rccrdpccl** [comment]
> @rccrdpccl Do you think its too much? I thought we send this data anyway, it might as well be nice looking. @osherdp WDYT?

Not sure that it is too much... Probably not at the moment. It is definitely nice, and a visual chart like those makes it easy to interpret the data itself. Not really an issue (at least not yet), but it is a bit "annoying" that we  need to maintain such charts and their kibana equivalent - and I was wondering where are we headed in regards to that.

**Comment by danmanor** [comment]
@rccrdpccl can you also approve ?

**Review by rccrdpccl — APPROVED** [review]

**Pull request merged**
