### PR TITLE
NO-ISSUE: Add parameters to the template

### PR DESCRIPTION
**Pull request by adriengentil**
This change adds suspend and schedule parameters because they will be
tuned for integration and stagging.

I also took the oportunity to fix the template and add a target in the
Makefile to lint it.

### CODE REVIEW

**Comment by rccrdpccl** [comment]
Maybe worth adding this check in prow in the future

**Comment by adriengentil** [comment]
> Maybe worth adding this check in prow in the future

yeah, I'll add it later, it's just that I need to download `oc`

**Pull request merged**
